server {
    listen 80;

    location /embed/v1/ {
        root /usr/share/nginx/html;
        add_header Access-Control-Allow-Origin *;

        location = /embed/v1/loader.js {
            root /usr/share/nginx/html;
            add_header Access-Control-Allow-Origin *;
            add_header Cache-Control "no-cache";
        }
    }
}
